plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.mirage.nearbytransport'
version = '0.1.0'

android {
  namespace "com.mirage.nearbytransport"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions { abortOnError false }
}

dependencies {
  implementation 'com.google.android.gms:play-services-nearby:19.5.0'
}
